run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tienpdinh/gpt-home)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/tienpdinh/gpt-home
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
      shadow:
        strict: false
    enable:
      - shadow
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - typecheck
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - test/fixtures
  exclude-files:
    - ".*_mock.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
        - gocyclo
        - errcheck
        - goconst
        - stylecheck
        - goimports
    - path: cmd/
      linters:
        - mnd
        - stylecheck
    - path: test/
      linters:
        - mnd
        - funlen
        - dupl
        - errcheck
  exclude-use-default: false
  exclude-case-sensitive: false
  include:
    - EXC0002
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info