coverage:
  status:
    project: off
    patch: off

  ignore:
    - "**/*_test.go"
    - "**/test/**"
    - "**/tests/**"
    - "**/mocks/**"
    - "**/vendor/**"
    - "cmd/main.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true