coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

  ignore:
    - "**/*_test.go"
    - "**/test/**"
    - "**/tests/**"
    - "**/mocks/**"
    - "**/vendor/**"
    - "cmd/main.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true