# Models PVC no longer needed - using Ollama on host PC
# Removed gpt-home-models-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-home-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path